# Generated by scripts/brew-formula.sh on release. Do not edit by hand:
# the next release overwrites it.
class ShipProven < Formula
  desc "Terminal client for ShipProven"
  homepage "https://github.com/Verrian/homebrew-shipproven"
  version "0.0.111"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://storage.googleapis.com/downloads-product-first/ship-proven/v0.0.111/ship-proven-darwin-arm64"
      sha256 "257ef0827f58501c34b26573f11dc4d07ee8478e211fc1a9b51739ad0484d226"
    end
    on_intel do
      url "https://storage.googleapis.com/downloads-product-first/ship-proven/v0.0.111/ship-proven-darwin-amd64"
      sha256 "7af8aeba9afd007887db2004c2b3b687993f78a27c59c7eac2687f22d40f66da"
    end
  end

  def install
    # The published asset is named per platform; install it under the one
    # name people type.
    bin.install Dir["ship-proven-darwin-*"].first => "ship-proven"
  end

  test do
    # `version` needs no cluster, no config and no network — the only
    # subcommand that can run in a sandbox with nothing set up.
    assert_match "0.0.111", shell_output("#{bin}/ship-proven version")
  end
end
