# Generated by scripts/brew-formula.sh on release. Do not edit by hand:
# the next release overwrites it.
class ShipProven < Formula
  desc "Terminal client for ShipProven"
  homepage "https://github.com/Verrian/homebrew-shipproven"
  version "0.0.139"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://storage.googleapis.com/downloads-product-first/ship-proven/v0.0.139/ship-proven-darwin-arm64"
      sha256 "826bece6df3eca104cacbab8353ea8b40d72ce5b7a03112ea291bd33e4668ded"
    end
    on_intel do
      url "https://storage.googleapis.com/downloads-product-first/ship-proven/v0.0.139/ship-proven-darwin-amd64"
      sha256 "f14dd8ef63b6550fbb5e3ae32c797a83d6c88ffa1fe29c9951b4e44ac45a491c"
    end
  end

  def install
    # The published asset is named per platform; install it under the one
    # name people type.
    bin.install Dir["ship-proven-darwin-*"].first => "ship-proven"
  end

  test do
    # `version` needs no cluster, no config and no network — the only
    # subcommand that can run in a sandbox with nothing set up.
    assert_match "0.0.139", shell_output("#{bin}/ship-proven version")
  end
end
